### ISSUE TITLE
Release notes created incorrectly

### ISSUE THREAD

**Issue by picosam** [conventional-changelog/releaser-tools#58]
Hello, is it normal that my releases lack proper formatting even though I'm correctly using Conventional Commit messages? See here please: https://github.com/coformatique/prisma-auth0-starter/releases

I'm using `conventional-github-releaser -p angular` as can be seen in my [package.json](https://github.com/coformatique/prisma-auth0-starter/blob/master/package.json#L14) file.

Thank you

**Comment by picosam** [comment]
...and when I tried removing all releases and regenerating then again using `conventional-github-releaser -p angular -r 0` I only got the last release generated and still incorrectly :(

**Comment by hbetts** [comment]
@picosam your release notes definitely look incorrect.

When looking through your `package.json` file I couldn't tell which version of `conventional-github-releaser` you are using. Could you provide that information please?

**Comment by picosam** [comment]
```
# Sammy at sacbookpro15.home in ~ [16:54:10]
→ conventional-github-releaser --version
2.0.2
```

**Comment by hbetts** [comment]
@picosam I suspect this is because of the way we now load preset packages in `conventional-changelog` (We use a [preset loader](https://github.com/conventional-changelog/conventional-changelog/blob/1cc079df803f58b52c8aa997fff43e9c162266e7/packages/conventional-changelog-preset-loader/index.js)). Can you please add `conventional-changelog-angular` as a development dependency of your package, and try running the `github-release` script again?

**Comment by picosam** [comment]
That didn't do it unfortunately. I ran the following commands:
```
github-remove-all-releases coformatique prisma-auth0-starter -t $CONVENTIONAL_GITHUB_RELEASER_TOKEN
yarn add conventional-changelog-angular --dev
```
The I committed and pushed and ran `yarn release` followed by `git push --follow-tags origin master`. That allowed `standard-version` to correctly generate the CHANGELOG.md file. Finally I ran `conventional-github-releaser -p angular -r 0` to generate all releases, and as you can see it didn't generate the final release correctly AND didn't generate the older releases 😞

**Comment by picosam** [comment]
Hello, any news about this?

**Comment by lmachens** [comment]
@hbetts I had the same issue. `npm i --save-dev conventional-changelog-angular` did the trick for me. thx!

**Comment by gmeans** [comment]
Adding `conventional-changelog-angular` as a dev dependency did not resolve this on my end.

**Comment by lmachens** [comment]
In a different project I faced this issue again.
Looks like the cli version is not working correctly. 

A simple node script works fine:

github-release.js
```
const conventionalGithubReleaser = require('conventional-github-releaser');

const auth = {
  type: 'oauth',
  token: 'xxxxx'
};

conventionalGithubReleaser(
  auth,
  {
    preset: 'angular'
  },
  console.info
);
```

call with `node github-release.js`.

**Comment by hbetts** [comment]
@picosam, can you please try the CLI using `--preset` instead of `-p`, and `--releaseCount` instead of `-r`?

(I suspect there may be an issue with our use of our command line flag library that's preventing it from interpreting the short form of the command line arguments.)

**Comment by hbetts** [comment]
Turns out this issue was reported in #63.

A fix has been accepted.

Successfully published:
 - conventional-github-releaser@3.1.1
 - conventional-gitlab-releaser@3.1.1
